src/library/create-texture-atlas.js, src/services/scene.tsx
Bug fix when exporting more than once, uvs were getting messed up
=> fix wrong uv 2nd export

src/components/Selector.tsx
Hi, I have a PR for fixing percent show when trait loading.
Please check and merge it.
Thanks
=> fix percent issue

src/styles/SelectorStyle.js
Fix the position of the cancel icon.
=> fix trait icon position

src/components/Editor.tsx
Hi, I fixed bugs. One line fixing. 😍👌👌
Please check.
=> fix index bug

src/components/BackButton.module.css, src/components/Editor.jsx, src/components/Landing.jsx, src/components/Scene.jsx, src/components/Selector.jsx, src/context/SceneContext.jsx, src/library/utils.js
=> Final details

src/components/Scene.jsx, src/components/Selector.jsx, src/context/SceneContext.jsx
update the joint rotation of the new trait to mouse position after assigning the new item
issue:
https://user-images.githubusercontent.com/60634884/212203758-79386970-7074-4b4b-a4cd-0a5f0fb2a6ee.mp4
result:
https://user-images.githubusercontent.com/60634884/212203905-0f8a8182-46c7-494d-888c-31974ff9c63b.mp4
=> Tcm reset joint

src/components/Selector.jsx, src/context/SceneContext.jsx
fix holes displaying when changing trait
=> fix cull meshes

src/components/App.jsx, src/components/Editor.jsx, src/components/Selector.jsx, src/context/SceneContext.jsx
-this pr fixes user being able to select while another trait is loading
-it also stops randomizing when turning on/off the ui
=> fix double trait select

src/components/App.jsx, src/components/ChatComponent.jsx
=> Fix various

src/library/merge-geometry.js
-This pr will help in combining vrm traits with different skeleton lengths
=> Merge multi bones

src/App.jsx, src/components/Editor.jsx, src/context/SceneContext.jsx, src/library/option-utils.js, src/pages/Appearance.jsx
-Moved the fetching options logic code from Editor.jsx to a option-utils.js to easily fetch random options
-Created a new function to call Random character traits
=> Extract logic from selector

src/components/ExportMenu.jsx
Fix https://github.com/webaverse-studios/CharacterCreator/issues/205
Hello @soulofmischief , how about these names ?
```
CharacterCreator_exported.glb
CharacterCreator_exported_unoptimized.glb
CharacterCreator_exported.vrm
```
=> Rename exported files.

src/library/VRMExporter.js, src/library/utils.js
Currently trying to load any downloaded vrm file from character creator will have 2 main issues, licenseUrl definition does not exsists (and will not load with default vrm loader), and visemes/blendshapes are not connected to correct node, (so no blink/mouth move will be present), this pr will fix this
=> Important Fix!!

index.html, public/style.css, src/pages/Bio.jsx, src/pages/Create.jsx, src/pages/Create.module.css
Reverts webaverse-studios/CharacterCreator#272
=> Revert "Yendor/flexbox"

src/components/Chat.jsx, src/pages/View.jsx
=> Fix for Speech recognition doesn't end when leaving Chat page

src/components/Selector.jsx
It's a little bit awkward if we could select the same trait. In this PR, I disable user to select the same trait.
issue:
https://user-images.githubusercontent.com/60634884/217965056-adc5e68a-9cdc-427d-a1f4-170fac9a74c9.mp4
result:
https://user-images.githubusercontent.com/60634884/217965074-29f01938-85de-4d1a-bf01-40a7dbf2c6b1.mp4
=> disable user to select the same trait

src/components/Scene.jsx
This pr will fix #292 limiting the user movement to character view area
=> clamp translation

src/library/screenshotManager.js
Correct encoding for screenshot
=> screenshot encoding

src/App.jsx, src/components/Mint.jsx, src/library/animationManager.js, src/pages/Mint.jsx
reset and pause for camera screenshot
=> Tcm screenshot encoding

src/App.jsx, src/components/Editor.jsx, src/components/Selector.jsx, src/context/SceneContext.jsx, src/library/option-utils.js, src/pages/Appearance.jsx
Removes `initialTraits`
cleanup on https://github.com/webaverse-studios/CharacterCreator/issues/304
=> remove intialTraits
